# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

google_id: 1000040334636-uohs489t2ndrgiv742tt0l3u2cafv0q2.apps.googleusercontent.com
google_secret: NtYbyXc-1XZNbPyOQKfh-yiu


vimeo_id: 265cb46f436a81f5d8a6ea991898df98b1ccb063
vimeo_secret: d7b7f66bfd4a565fcad1b3b9c23446e2b32f8f04
vimeo_token: c54317838752b29b6cd05e48b0f85480
vimeo_username: EZOnline Development


REDISTOGO_URL: 'redis://redistogo:e70c78075fc102bbed92674e5475c725@scat.redistogo.com:10374/'

development:
  vimeo_redirect_uri: 'http://ezonline-dev.com:3000/vauthentication'
  google_redirect_uri: 'http://ezonline-dev.com:3000/authentication'
production:
  vimeo_redirect_uri: 'http://ezonline.herokuapp.com/vauthentication'
  google_redirect_uri: 'http://ezonline.herokuapp.com/authentication'