# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82c2cf8ddc47545bc5d74e18a541f4c2acf6509b06da1e5e5773a5c116518317f71f08845ce670ed1193f88e3bb71ab1d42d4bf3f77f176bd9a23c0627c1c5cb
  google_id: 1000040334636-uohs489t2ndrgiv742tt0l3u2cafv0q2.apps.googleusercontent.com
  google_secret: NtYbyXc-1XZNbPyOQKfh-yiu
  vimeo_id: 265cb46f436a81f5d8a6ea991898df98b1ccb063
  vimeo_secret: d7b7f66bfd4a565fcad1b3b9c23446e2b32f8f04
  vimeo_token: c54317838752b29b6cd05e48b0f85480
  vimeo_username: EZOnline Development

test:
  secret_key_base: 2ae7a57bc0ac187939462104b77034e0a4a4813583f09067562f8a50f77d3821dccfe8249d193c1771aa5e46c694608dcdaa6b166bd75a86e58f01a13a388077
  google_id: 1000040334636-uohs489t2ndrgiv742tt0l3u2cafv0q2.apps.googleusercontent.com
  google_secret: NtYbyXc-1XZNbPyOQKfh-yiu
  vimeo_id: 265cb46f436a81f5d8a6ea991898df98b1ccb063
  vimeo_secret: d7b7f66bfd4a565fcad1b3b9c23446e2b32f8f04
  vimeo_token: c54317838752b29b6cd05e48b0f85480
  vimeo_username: EZOnline Development

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
